### PR TITLE
fix ci with sleep

### PR DESCRIPTION
**Pull request by ezpuzz**
want to see if this fixes CI.  it seems like resolve requests are only processed if there are new ones maybe?

see: https://github.com/amethyst/atelier-assets/compare/master...radium-io:resolve-fix?expand=1

### CODE REVIEW

**Comment by ezpuzz** [comment]
wound up just adding a sleep after starting the daemon so that the meta files are generated before calling load.  this avoids the race condition mentioned on discord

**Comment by ezpuzz** [comment]
@jlowry if we merge this I will merge the amethyst PR and we can keep additional prefab work on a new branch.  The new assets pipeline will unblock some more of the examples and I can move over to working on the book.

**Comment by ezpuzz** [comment]
actually should probably get SpriteSheets working first, merging legion_v2 in and trying for that now

**Comment by jlowry** [comment]
> @jlowry if we merge this I will merge the amethyst PR and we can keep additional prefab work on a new branch. The new assets pipeline will unblock some more of the examples and I can move over to working on the book.

I'm happy to split the additional prefab work into a separate PR.

**Comment by ezpuzz** [comment]
@jlowry ok I think good to merge now.  pretty much all non-prefab stuff is working now.

**Pull request closed without merging**
